# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 759)
        MainWindow.setStyleSheet("QPushButton:hover{\n"
"    background-color: white;\n"
"    color: crimson;\n"
"}\n"
"QPushButton{\n"
"    background-color: darkblue;\n"
"    color:darkorange;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tblwListen = QtWidgets.QTableWidget(self.centralwidget)
        self.tblwListen.setGeometry(QtCore.QRect(20, 360, 931, 341))
        self.tblwListen.setRowCount(50)
        self.tblwListen.setColumnCount(7)
        self.tblwListen.setObjectName("tblwListen")
        self.lblStdnt = QtWidgets.QLabel(self.centralwidget)
        self.lblStdnt.setGeometry(QtCore.QRect(150, 100, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblStdnt.setFont(font)
        self.lblStdnt.setObjectName("lblStdnt")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(170, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.lblSurname = QtWidgets.QLabel(self.centralwidget)
        self.lblSurname.setGeometry(QtCore.QRect(150, 160, 76, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurname.setFont(font)
        self.lblSurname.setObjectName("lblSurname")
        self.lblSchool = QtWidgets.QLabel(self.centralwidget)
        self.lblSchool.setGeometry(QtCore.QRect(170, 190, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSchool.setFont(font)
        self.lblSchool.setObjectName("lblSchool")
        self.lblPhone = QtWidgets.QLabel(self.centralwidget)
        self.lblPhone.setGeometry(QtCore.QRect(170, 220, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPhone.setFont(font)
        self.lblPhone.setObjectName("lblPhone")
        self.lblAdress = QtWidgets.QLabel(self.centralwidget)
        self.lblAdress.setGeometry(QtCore.QRect(400, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblAdress.setFont(font)
        self.lblAdress.setObjectName("lblAdress")
        self.lneStudentAdress = QtWidgets.QLineEdit(self.centralwidget)
        self.lneStudentAdress.setGeometry(QtCore.QRect(470, 100, 271, 141))
        self.lneStudentAdress.setObjectName("lneStudentAdress")
        self.lneStudentPhnNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lneStudentPhnNumber.setGeometry(QtCore.QRect(230, 220, 133, 22))
        self.lneStudentPhnNumber.setObjectName("lneStudentPhnNumber")
        self.lneStudentSchool = QtWidgets.QLineEdit(self.centralwidget)
        self.lneStudentSchool.setGeometry(QtCore.QRect(230, 190, 133, 22))
        self.lneStudentSchool.setObjectName("lneStudentSchool")
        self.lneStudentSurname = QtWidgets.QLineEdit(self.centralwidget)
        self.lneStudentSurname.setGeometry(QtCore.QRect(230, 160, 133, 22))
        self.lneStudentSurname.setObjectName("lneStudentSurname")
        self.lneStudentName = QtWidgets.QLineEdit(self.centralwidget)
        self.lneStudentName.setGeometry(QtCore.QRect(230, 130, 133, 22))
        self.lneStudentName.setObjectName("lneStudentName")
        self.lneStudentIdent = QtWidgets.QLineEdit(self.centralwidget)
        self.lneStudentIdent.setGeometry(QtCore.QRect(230, 100, 133, 22))
        self.lneStudentIdent.setObjectName("lneStudentIdent")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(110, 290, 121, 61))
        self.btnAdd.setObjectName("btnAdd")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(230, 290, 121, 61))
        self.btnDelete.setObjectName("btnDelete")
        self.btnSearch = QtWidgets.QPushButton(self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(590, 290, 121, 61))
        self.btnSearch.setObjectName("btnSearch")
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(350, 290, 121, 61))
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnLists = QtWidgets.QPushButton(self.centralwidget)
        self.btnLists.setGeometry(QtCore.QRect(470, 290, 121, 61))
        self.btnLists.setObjectName("btnLists")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(710, 290, 121, 61))
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mehmet Demirel - Student Registration Program"))
        self.lblStdnt.setText(_translate("MainWindow", "Number :"))
        self.lblName.setText(_translate("MainWindow", "Name :"))
        self.lblSurname.setText(_translate("MainWindow", "Surname :"))
        self.lblSchool.setText(_translate("MainWindow", "School :"))
        self.lblPhone.setText(_translate("MainWindow", "Phone :"))
        self.lblAdress.setText(_translate("MainWindow", "Adress : "))
        self.btnAdd.setText(_translate("MainWindow", "Add Student"))
        self.btnDelete.setText(_translate("MainWindow", "Delete Student"))
        self.btnSearch.setText(_translate("MainWindow", "Search Student"))
        self.btnUpdate.setText(_translate("MainWindow", "Update Student"))
        self.btnLists.setText(_translate("MainWindow", "List Student"))
        self.btnExit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
